### ISSUE TITLE
Incorrect Balance

### ISSUE THREAD

**Issue by 1001WordsPhoto** [startailcoon/Gridcoinstats#40]
Happy New Year! Since the change to the latest Gridcoin version, the balance listed on my CPID page has been incorrect. My wallet says I have about 8,000 GRC, which was very close to what the Gridcoin Stats page said before the update. Now the Stats page says I have 265 943.59 GRC, and last week it said I had over 1 million GRC. If I look at the Gridcoin Address List, on page 9 there is a balance of 265 943.59 for a different address. In that address (SCPvmUYoZFHNqvw6524Uz4EdxxQPD54VKA) there are 61 additional addresses, one of which is mine. The CPID address and the Gridcoin Address are both in my wallet. 

Maybe my address transacted coins with another address through this address? 

Thank you for the website, and all your hard work.

Matthew

**Comment by startailcoon** [comment]
There have been other reports of the same issue and it has been addressed for the next update (due end of jan). 

The issue was due to an error when output addresses where linked incorrectly in some transactions (contracts). This made a bunch of addresses be regarded as related on the page.
