### ISSUE TITLE
testnet faucet is showing gridcoin invalid

### ISSUE THREAD

**Issue by givianw** [startailcoon/Gridcoinstats#43]
when i submit gridcoin `SK7A2yq4rsoDSKc592dxSb3JSYeSSopbNB` at [testnet](https://testnet.gridcoinstats.eu/faucet/submit), it shows as invalid gridcoin.

**Comment by KeithMyers** [comment]
That is not a testnet address.  Use a receive address from your testnet wallet.

**Comment by givianw** [comment]
@KeithMyers perhaps my words are misleading. i have submitted my Gridcoin wallet address at given hyperlink in op:

`By submitting the following form with a Gridcoin wallet address you will receive free Gridcoin.`

**Comment by barton2526** [comment]
The faucet is for the Gridcoin testnet.  This is a **separate blockchain** for testing purposes.  It does not give real Gridcoin.

**Comment by givianw** [comment]
@ barton2526 thanks a lot

**Comment by barton2526** [comment]
@startailcoon perhaps this should be clarified further on the page
