### ISSUE TITLE
Poll vote verification page shows zero balance

### ISSUE THREAD

**Issue by sibebleuze** [startailcoon/Gridcoinstats#47]
Recently I got to know of the existence of the [Polls section](https://www.gridcoinstats.eu/poll) on Gridcoinstats. For the last two or three votes, I went and checked the vote verification page on my own vote. I noticed that at first, it showed my vote as invalid. After a while, I presume at the next superblock, it became valid with my vote weight purely based on magnitude. Balance still showed zero. I first thought this was because of the 16 hour window where coins aren't mature, but even after this the zero balance remained. Both of these things, being invalid at first and balance remaining zero, do not show up for the largest part of other voters that I looked at on Gridcoinstats.
My question is if this vote weight represents what is my actual vote weight is or if Gridcoinstats can't find some connections between addresses and that's why the balance doesn't show. Because in the latter case, there isn't really a problem, the voting system can still see my correct vote weight and I'll just have to live with not being able to see it on Gridcoinstats for some reason. However, if it is the first case and my balance vote weight is actually zero, I would like to know why that is and what I need to do to get it to represent my actual balance.
Below I list two of the vote verification pages of votes I recently participated in, so you can see for yourself what I mean and maybe you'll be able to tell me what's going on that I don't understand yet:

- https://www.gridcoinstats.eu/pollverify/3c1031912b99ee875f68c952039764e688c58a333055d6242584e2474864ed10
- https://www.gridcoinstats.eu/pollverify/8b16eef91e0ffbc1d012a65538ad7c118f126f85f1683413f2b9bf39909d6046

Thanks already if you just take a look at it. I just didn't really know where to go with questions like these and your repo seemed like a good place to start.

**Comment by KeithMyers** [comment]
Startail will chime in I'm sure, but it is a well known fact that the website can't identify all addresses associated with a wallet.
And therefore,  there is no guarantee that the balances shown on the website match the actual balance in the wallet.

**Comment by sibebleuze** [comment]
Wow, I read your answer days ago, I just didn't realise until now I should probably close this. Thanks for the help/info/reassurance that everything is just fine.
